### ISSUE TITLE
hll_compute and hll_merge_compute not coinciding

### ISSUE THREAD

**Issue by mingot** [amirtuval/mysql-hyperloglog#1]
I have just tried to reproduce your exmple.sql and I have encountered a problem when estimating the value through hll_merge_compute. Although hll_compute works very well, hll_create + hll_merge_compute seems to produce extrange results. This is the merged output of your example:

+------------------+----------+-------------------+-----------------+
| date(visit_time) | accurate | estimated_compute | estimated_merge |
+------------------+----------+-------------------+-----------------+
| 09/06/14         |     1119 |              1138 |             231 |
| 10/06/14         |     1168 |              1141 |             235 |
| 11/06/14         |     1231 |              1240 |             236 |
| 12/06/14         |     1219 |              1226 |             236 |
| 13/06/14         |     1158 |              1191 |             235 |
| 14/06/14         |     1208 |              1257 |             237 |
| 15/06/14         |     1159 |              1102 |             235 |
| 16/06/14         |     1167 |              1172 |             236 |
+------------------+----------+-------------------+-----------------+

Any idea what can be causing the error? 
I am runing MySQL 5.5.29 on OSX 10.9.5.

Thank you!

**Comment by mingot** [comment]
I have just undone you last commit 'add support for serializing to binary strings (no base64)' and works as aspected when hll is stored as base64 string, so you must have some error in this last one that I have been unable to find.

**Comment by amirtuval** [comment]
Thanks a lot for your feedback.

I'll take a look

**Comment by amirtuval** [comment]
Fixed. I'd really appreciate if you can test and let me know if there are issues

**Comment by mingot** [comment]
Works great, thanks!!
