### ISSUE TITLE
Wrong default bumber of buckets

### ISSUE THREAD

**Issue by Alexxz** [amirtuval/mysql-hyperloglog#3]
Documentation says

> If you would like to change the bit width of the HyperLogLog algorithm, you can change it by editing  the constants.hpp file before compiling the project.
> The default is 12, resulting in 2**12(4096) bytes of storage. This can go as high as 16 to get better accuracy with more storage, or you can lower it to save storage.

But in fact constant is HLL_NEW_BIT_WIDTH, stored in libmysqlhll/mysqlhll.cxx and is equal to 10
And that means 2**10(1024) bytes are used

And this value gives pretty annoying error value on simulations

**Comment by amirtuval** [comment]
Thanks.

Fixed the docs

**Comment by Alexxz** [comment]
Please fix additionally constant name and its path. When I tried to change referenced constant, nothing has changed.

**Comment by amirtuvalyallo** [comment]
Fixed
