### ISSUE TITLE
MySQL fails if you try to use more than 16 bits

### ISSUE THREAD

**Issue by Alexxz** [amirtuval/mysql-hyperloglog#4]
I've tried to set HLL_NEW_BIT_WIDTH to 17 and 18 - it results to 
mysql> SELECT hll_compute(val) FROM my_table WHERE id < 100;
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by amirtuval** [comment]
Thank you for the feedback.

I am not sure if hyperloglog was meant to be used with such large numbers.
A hyperloglog with width 18 will require 256kb to be stored for each record you saved - which requires a lot of IO and memory if you have many of them.

If you require this level of accuracy - I am not sure hyperloglog is what you need.

I doubt I'll have time to look at it any time soon. I suspect it is a memory issue, but it also could be just a bug in the code.
If you care to debug and submit a patch, I'd be happy to review it.

**Comment by Alexxz** [comment]
Thank you for quick reply.
Currently I'm just investigating opportunities of HLL algorithm, and I really understand that 256K sounds strange here. And I understand that with such memory I can precicely compute 64K integers.

I'm making simulations to get error distributions and  trying to put its bound below pretty low treshold.
But values I'm going to compute have cardinality around 10M so it can worth such memory consumption.

I'll try to investigate the issue on my own of cource. And I'll really appreciate your help.

**Comment by Alexxz** [comment]
Yep, this limitation is hardcoded constant of HLL implementation used. I've requsted comments on it here https://github.com/hideo55/cpp-HyperLogLog/issues/6

Thank you very much.
